#!/usr/bin/env python

Import('env')
module_env = env.Clone()



# Godot sources
sources = [
"register_types.cpp",

"port_audio_server.cpp",
]

# Static compilation
module_env.add_source_files(env.modules_sources, sources)
module_env.add_source_files(env.modules_sources, "portaudio/*.c")

